run:employee_test.cpp employee.cpp engineer.cpp manager.cpp trainee.cpp
	g++ employee_test.cpp employee.cpp engineer.cpp manager.cpp trainee.cpp employee.h engineer.h manager.h trainee.h -lgtest -lgtest_main -lpthread -o all.out

test:
	./all.out
